#### general settings
name: WU
train_type: what-uncertainties
eval_type: bnn
gpu_ids: [2]


#### datasets
dataset:
  image_size: 64
  in: "diabetes_train"
  test_in: "diabetes_test_in"
  ood: "diabetes_test_ood"
#### Checkpoint settings
checkpoints:
  path: "./checkpoints/BLeNet_WU_Diabetes/"
  save_checkpoint_freq: 2


#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.0005  # Learning rate
  weight_decay: 0.001

#### training settings: learning rate scheme, loss, optimizer
train:
  model_name: "BLeNet"

  is_de: True  # Whether or not apply deep ensembles

  num_epochs: 100
  batch_size: 128
  train_size: 1

  prior_mu: 0
  prior_sigma: 0.01
  posterior_mu_initial: [ 0, 0.05 ]
  posterior_rho_initial: [ -5, 0.01 ]


  in_channels: 1
  out_channels: 2

  loss: "ELBO"
