#### general settings
name: ARHT
train_type: arht-uncertainty
eval_type: bnn
gpu_ids: [2]


#### datasets
dataset:
  image_size: 64
  in: "diabetes_train"
  test_in: "diabetes_test_in"
  ood: "diabetes_test_ood"

#### Checkpoint settings
checkpoints:
  path: "./checkpoints/BLeNet_ARHT_diabetes/"
  save_checkpoint_freq: 2


#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.0005  # Learning rate
  weight_decay: 0.001

#### training settings: learning rate scheme, loss, optimizer
train:
  model_name: "BLeNet"
  task: "ood"

  num_epochs: 100
  batch_size: 200
  train_size: 1

  n_normal_samples: 5
  n_testing_samples: 200

  beta: 0.0001
  prior_mu: 0
  prior_sigma: 0.01
  posterior_mu_initial: [0, 0.05]
  posterior_rho_initial: [-3.5, 0.01]

  init_lambda: 0.01

  in_channels: 3
  out_channels: 2

  loss: "ELBO"
