#### general settings
name: WU
train_type: what-uncertainties-sim
eval_type: bnn
gpu_ids: [2]


#### datasets
dataset:
  image_size: 32
  in: "Gaussian_train"
  test_in: "Gaussian_test_in"
  ood: "Gaussian_test_ood"

#### Checkpoint settings
checkpoints:
  path: "./checkpoints/BMLP_Simulation/"
  save_checkpoint_freq: 2


#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.001  # Learning rate
  weight_decay: 0.001

#### training settings: learning rate scheme, loss, optimizer
train:
  model_name: "BMLP"
  task: "ood"

  num_epochs: 100
  batch_size: 236
  train_size: 1
  n_blocks: 2

  is_de: True

  n_normal_samples: 5
  n_testing_samples: 200

  beta: 0.0001
  prior_mu: 0
  prior_sigma: 0.01
  posterior_mu_initial: [0, 0.05]
  posterior_rho_initial: [-3, 0.01]

  in_channels: 128
  out_channels: 1

  loss: "ELBO"


#### Logging
logging:
  mode: disabled # disabled
  tags: [
      "BMLP",
      "WU",
      "OOD"
    ]