#### general settings
name: BPN
train_type: mcd-sim
eval_type: bnn
gpu_ids: [2]


#### datasets
dataset:
  image_size: 64
  in: "Gaussian_train"
  test_in: "Gaussian_test_in"
  ood: "Gaussian_test_ood"

#### Checkpoint settings
checkpoints:
  path: "./checkpoints/LeNet_MCD_Simulation/"
  save_checkpoint_freq: 2


#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.0005  # Learning rate
  weight_decay: 0.001

#### training settings: learning rate scheme, loss, optimizer
train:
  model_name: "MLP"

  num_epochs: 100
  batch_size: 128
  train_size: 1

  n_blocks: 2
  in_channels: 128
  out_channels: 1

  n_testing_samples: 200

  loss: "ELBO"

#### Logging
logging:
  mode: disabled # disabled, online
  tags: [
      "MLP",
      "ARHT",
      "OOD"
    ]
