#### general settings
name: Ensembles
train_type: ensembles
eval_type: bnn
gpu_ids: [2]


#### datasets
dataset:
  image_size: 32
  in: "CIFAR10"
  ood: "SVHN"

#### Checkpoint settings
checkpoints:
  path: "./checkpoints/LeNet_Ensembles_CIFAR10_SVHN/"
  save_checkpoint_freq: 2


#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.0005  # Learning rate
  weight_decay: 0.001

#### training settings: learning rate scheme, loss, optimizer
train:
  model_name: "LeNet"

  is_de: True  # Whether or not apply deep ensembles
  n_models: 5

  num_epochs: 100
  batch_size: 128
  train_size: 1

  in_channels: 3
  out_channels: 10

  loss: "ELBO"
