#### general settings
name: EDL
train_type: edl
eval_type: bnn
gpu_ids: [2]


#### datasets
dataset:
  image_size: 32
  in: "ImageNet"
  ood: "CIFAR10"

#### Checkpoint settings
checkpoints:
  path: "./checkpoints/LeNet_EDL_CIFAR10_ImageNet/"
  save_checkpoint_freq: 2


#### Optimizer settings
optimizer:
  opt_method: "ADAM"
  lr: 0.0005  # Learning rate
  weight_decay: 0.001

#### training settings: learning rate scheme, loss, optimizer
train:
  model_name: "LeNet"

  num_epochs: 100
  batch_size: 128
  train_size: 1

  in_channels: 3
  out_channels: 200

  loss: "ELBO"

#### Logging
logging:
  mode: online # disabled
  tags: [
      "LeNet",
      "EDL",
      "OOD"
    ]
